### ISSUE TITLE
FloatingWindow row height needs to take tabline into consideration

### ISSUE THREAD

**Issue by ajpeacock0** [Rasukarusan/vim-block-paste#4]
If the tabline is present, the Floating Window will be off by 1. This can easily repro'd by adding `set showtabline=2` for always show tabline.

Inside the function `block_paste#create_block()` there should be a check around `let row = start.y - 1` to consider is the tabline is displayed.

![Starting Lines](https://user-images.githubusercontent.com/7133924/104663891-d2f5e680-5682-11eb-8fb0-cf957660c559.png)

![After Block is ran](https://user-images.githubusercontent.com/7133924/104663921-e0ab6c00-5682-11eb-9999-0eaf156e5825.png)

Found on
```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

**Comment by Rasukarusan** [comment]
@ajpeacock0 
Hi there.
Thanks for the detailed measurements and screenshots!

I fixed, thanks!
